### ISSUE TITLE
dry css

### ISSUE THREAD

**Issue by franfranfranfran** [Jahmad730/prj-rev-bwfs-dasmoto#1]
https://github.com/Jahmad730/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L8
https://github.com/Jahmad730/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L27
etc...

try to keep in mind dry principles when setting your css. are there any elements on the page that should not receive the helvetica font-family? can you set this styling just once for the entire page?

are there any other bits of styling you can avoid repeating? how about any styling that is redundant - you set the styling for the brush h2 mutliple times as an example.

**Comment by Jahmad730** [comment]
I noticed the redundancy before submission, but I wanted to see what the feedback of redundancy is.  Whether it is an issue with simpler sites like these, and whether or not it is simply just a good habit to remove redundancy wherever we see it.
