### ISSUE TITLE
img alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [Jahmad730/prj-rev-bwfs-dasmoto#2]
https://github.com/Jahmad730/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L31
etc...

make sure to use an alt attribute for each img element to ensure that a wider variety of users have access to the information contained in those images. more info can be found [here](https://www.w3schools.com/tags/att_img_alt.asp)

**Comment by Jahmad730** [comment]
I see, thanks for clarifying that.
